# Generated by Django 5.2.17 on 2026-09-30 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='nazwa')),
                ('slug', models.SlugField(unique=True, verbose_name='adres')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='kolejność')),
            ],
            options={
                'verbose_name': 'kategoria',
                'verbose_name_plural': 'kategorie',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nazwa')),
                ('slug', models.SlugField(unique=True, verbose_name='adres')),
                ('description', models.TextField(blank=True, verbose_name='opis')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='cena (zł)')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='cena promocyjna (zł)')),
                ('image', models.CharField(blank=True, help_text='Adres zdjęcia (np. skopiowany z produktu w Shoperze) albo plik z public/images/sklep/, np. /images/sklep/buty.jpg', max_length=500, verbose_name='zdjęcie')),
                ('sizes', models.CharField(blank=True, help_text='Po przecinku, np. S, M, L, XL albo 40, 41, 42.', max_length=200, verbose_name='rozmiary')),
                ('badge', models.CharField(blank=True, help_text='Np. Nowość, Bestseller.', max_length=20, verbose_name='etykieta')),
                ('buy_url', models.URLField(blank=True, help_text='Adres tego produktu w sklepie Shoper.', verbose_name='link do zakupu')),
                ('is_active', models.BooleanField(default=True, verbose_name='widoczny')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='kolejność')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.category', verbose_name='kategoria')),
            ],
            options={
                'verbose_name': 'produkt',
                'verbose_name_plural': 'produkty',
                'ordering': ('order', 'name'),
            },
        ),
    ]
