# Generated by Django 5.2.17 on 2026-09-30 12:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(help_text='Np. CrossFit, Hyrox, Trening Siłowy.', max_length=60, verbose_name='program')),
                ('name', models.CharField(max_length=120, verbose_name='nazwa')),
                ('slug', models.SlugField(help_text='Część adresu strony, np. hyrox-sim.', unique=True, verbose_name='adres')),
                ('description', models.TextField(blank=True, help_text='Na czym polega trening, standardy ruchów.', verbose_name='opis')),
                ('score_type', models.CharField(choices=[('time', 'Czas (mniej = lepiej)'), ('reps', 'Powtórzenia (więcej = lepiej)'), ('weight', 'Ciężar w kg (więcej = lepiej)')], max_length=10, verbose_name='typ wyniku')),
                ('is_active', models.BooleanField(default=True, help_text='Nieaktywne treningi są ukryte.', verbose_name='aktywny')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='kolejność')),
            ],
            options={
                'verbose_name': 'trening',
                'verbose_name_plural': 'treningi',
                'ordering': ('program', 'order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='wynik')),
                ('performed_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='data')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='notatka')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dodano')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL, verbose_name='zawodnik')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ranking.workout', verbose_name='trening')),
            ],
            options={
                'verbose_name': 'wynik',
                'verbose_name_plural': 'wyniki',
                'ordering': ('-performed_on', '-created_at'),
            },
        ),
    ]
